package com.esecchi.common.model.order;

public enum OrderStatus {
    WAITING_FOR_STOCK_RESERVATION,
    WAITING_FOR_PAYMENT,
    COMPLETED,
    CANCELLED_INSUFFICIENT_STOCK,
    CANCELLED_INVENTORY_ERROR,
    CANCELLED_PAYMENT_FAILED
}