server:
  port: 8081

spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sales_platform_user_auth_db
    username: postgres
    password: 41542654
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      user-created: "sp.user.created"

# Registro en el server Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuración de JWT
jwt:
  secret: RVHHaVOsiyMXsE1TwnpWtGGiIEz2mlE5WlGfcDYC6Hc
  expiration: 3600000

# Configuración para autenticar servicios y que puedan consumir la API sincrónicamente
internal:
  services:
    clients:
      notification-service: vg2fDaZam16JUmrArRc5nmNMZCPKFsvWB9e77mnF2xN