server:
  port: 8082

spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    openfeign:
      client:
        config:
          user-auth-service:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: full
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "notification-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.esecchi.*"
    topics:
      user-created: "sp.user.created"
      user-email-updated: "sp.user.email.updated"
      order-cancelled: "sp.order.cancelled"
      order-completed: "sp.order.completed"

# Registro en el server Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuración de JWT
jwt:
  expiration: 3600000

# Configuración de la clave para autenticarse frente al microservicio de user-auth.
internal:
  auth:
    secret: vg2fDaZam16JUmrArRc5nmNMZCPKFsvWB9e77mnF2xN