server:
  port: 8083

spring:
  application:
    name: product-inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sales_platform_product_inventory_db
    username: postgres
    password: 41542654
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "product-inventory-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.esecchi.*"
    topics:
      order-created: "sp.order.created"
      stock-reservation: "sp.productinventory.reservation.result"

# Registro en el server Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/